name: Validate Infra

on:
  push:
    branches:
      - main

env:
  TERRAFORM_VERSION: 1.12.1
  TERRAFORM_DIR: infra

jobs:
  # JOB 1: Setup AWS and install Terraform
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Test AWS Connection (Get Caller Identity)
        run: |
          aws sts get-caller-identity

      - name: Install Terraform
        run: |
          wget https://releases.hashicorp.com/terraform/${{ env.TERRAFORM_VERSION }}/terraform_${{ env.TERRAFORM_VERSION }}_linux_amd64.zip
          unzip terraform_${{ env.TERRAFORM_VERSION }}_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
          terraform -version

      - name: Change directory to infra
        run: |
          cd ${{ env.TERRAFORM_DIR }}
          terraform init
          terraform validate
          terraform plan