name: Deploy Infra

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Select action'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy
          - setup
  push:
    branches:
      - main
      - feature/basicPlatform

env:
  TERRAFORM_VERSION: 1.5.7
  TERRAFORM_DIR: infra

jobs:
  # JOB 1: Setup AWS and install Terraform
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # - name: Install aws cli v2
      #   run: |
      #     curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      #     unzip awscliv2.zip
      #     sudo ./aws/install

      - name: Test AWS Connection (Get Caller Identity)
        run: |
          aws s3 ls
        # This will fail if credentials are invalid

      - name: Install Terraform
        run: |
          wget https://releases.hashicorp.com/terraform/${{ env.TERRAFORM_VERSION }}/terraform_${{ env.TERRAFORM_VERSION }}_linux_amd64.zip
          unzip terraform_${{ env.TERRAFORM_VERSION }}_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
          terraform -version

      - name: Change directory to infra
        run: |
          cd ${{ env.TERRAFORM_DIR }}
          terraform init
          terraform validate
          terraform plan

  # JOB 4: Manual terraform apply
  terraform_apply:
    if: github.event_name == 'workflow_dispatch' && contains(github.event.inputs.action, 'apply')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install aws cli v2
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

      - name: Test AWS Connection (Get Caller Identity)
        run: |
          aws s3 ls
        # This will fail if credentials are invalid

      - name: Install Terraform
        run: |
          wget https://releases.hashicorp.com/terraform/${{ env.TERRAFORM_VERSION }}/terraform_${{ env.TERRAFORM_VERSION }}_linux_amd64.zip
          unzip terraform_${{ env.TERRAFORM_VERSION }}_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
          terraform -version

      - name: Change directory to infra
        run: |
          cd ${{ env.TERRAFORM_DIR }}
          terraform init
          terraform validate
          terraform plan

      - name: Terraform Apply
        run: |
          cd ${{ env.TERRAFORM_DIR }}
          terraform apply -auto-approve \
            -var="dummy_variable1=value1" \
            -var="dummy_variable2=value2"

  # JOB 5: Manual terraform destroy
  terraform_destroy:
    if: github.event_name == 'workflow_dispatch' && contains(github.event.inputs.action, 'destroy')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install aws cli v2
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

      - name: Test AWS Connection (Get Caller Identity)
        run: |
          aws s3 ls
        # This will fail if credentials are invalid

      - name: Install Terraform
        run: |
          wget https://releases.hashicorp.com/terraform/${{ env.TERRAFORM_VERSION }}/terraform_${{ env.TERRAFORM_VERSION }}_linux_amd64.zip
          unzip terraform_${{ env.TERRAFORM_VERSION }}_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
          terraform -version

      - name: Change directory to infra
        run: |
          cd ${{ env.TERRAFORM_DIR }}
          terraform init
          terraform validate
          terraform plan

      - name: Terraform Apply
        run: |
          cd ${{ env.TERRAFORM_DIR }}
          terraform destroy -auto-approve \
            -var="dummy_variable1=value1" \
            -var="dummy_variable2=value2"
